### ISSUE TITLE
Hiding of Client secret

### ISSUE THREAD

**Issue by KieranBond** [KieranBond/MiniSpotify#15]
#31

**Comment by Gusted** [comment]
Explain it a bit more I only see Client ID and not an secret

**Comment by Gusted** [comment]
Ah I see client secret, I think the best you can do to make it that the users need to setup an application at their own with their own client ID/Secret to hide the key in code with encryption is crack able.

**Comment by KieranBond** [comment]
> Ah I see client secret, I think the best you can do to make it that the users need to setup an application at their own with their own client ID/Secret to hide the key in code with encryption is crack able.

We can't do this, as the Client Secret is provided by Spotify for this specific application - To help track malicious intent and other usage. 

There are two problems; 
 * The secret is sent in the connection request
* The secret is needed in the builds to make the app function.
  - Perhaps some file encryption can help reduce issues with this second point.

So, ideally there needs to be a better way of hiding it than just not pushing it to the repository.
