### ISSUE TITLE
Like Song Button

### ISSUE THREAD

**Issue by GabrielCoteM** [KieranBond/MiniSpotify#20]
Hi!

I've been looking for a mini Spotify player for Windows since a while and this one seems to fit the bill almost perfectly! I'll start using it!

What I would like to have is a button to like or unlike the currently playing song. Could I start working on that feature?

Thank you and keep up the good work!

**Comment by KieranBond** [comment]
@GabCM I'm glad you like the app - I built it for the exact reason that I couldn't find one that suited me.

On that note, please feel free to contribute as much as you like - Just take a look at [the contributing section](https://github.com/KieranBond/MiniSpotify#contribution-guidelines) and the [code of conduct](https://github.com/KieranBond/MiniSpotify/blob/development/CODE_OF_CONDUCT.md). 

Assign me to the pull request when it's ready and I'll take a look!

Thanks for the contribution :)

**Comment by KieranBond** [comment]
Oh and sorry for the slow reply - I didn't receive an email!

**Comment by GabrielCoteM** [comment]
Many thanks! I'll get to it soon then!

**Comment by KieranBond** [comment]
@GabCM any issues, then please feel free to comment here!
