### ISSUE TITLE
[BUG] Low quality album art

### ISSUE THREAD

**Issue by GabrielCoteM** [KieranBond/MiniSpotify#24]
**Describe the bug**

The album art looks very pixelated on the main interface.

---

**To Reproduce**

1. Open the application
2. Play some music

---

**Expected behavior**

The album art shows up smoothly instead of pixelated.

---

**Screenshots**

![Annotation 2019-11-20 142533](https://user-images.githubusercontent.com/5678332/69270779-a559fe00-0ba1-11ea-8cb4-6f90b771068c.png)

---

Some possible fixes I have in mind:
- Use [BitmapScalingMode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.bitmapscalingmode?view=netframework-4.7.2) to define a proper image scaling algorithm.
- Add the [Magick.NET](https://github.com/dlemstra/Magick.NET) library and use its scaling features.

I'd be more inclined to try the BitmapScalingMode solution first, since it seems to be built-in the .NET Framework. I've used the Magick.NET library before for a personal image-related project.

**Comment by KieranBond** [comment]
I've noticed this before too but forgotten to flag it. 

Feel free to have a bash at it - the solutions you've provided sound good.

Just before you do those attempts, check the image size is a power of 2 and if not then try making it so and see how it looks then.

**Comment by GabrielCoteM** [comment]
> I've noticed this before too but forgotten to flag it.
> 
> Feel free to have a bash at it - the solutions you've provided sound good.
> 
> Just before you do those attempts, check the image size is a power of 2 and if not then try making it so and see how it looks then.

Oh yeah, great idea as well! I'll try the power of 2 idea first.
