### ISSUE TITLE
[FEATURE] Debug Logging

### ISSUE THREAD

**Issue by KieranBond** [KieranBond/MiniSpotify#26]
* **Is your feature request related to a problem? Please describe.**

When errors occur within the app, we currently write to the Console - This is useless as it doesn't output to any file that can be submitted.

---

* **Describe the solution you'd like**

A Logging class that writes all logs to a file and is easily called within the code.

--- 

* **Describe alternatives you've considered**

None.

**Comment by aseemsahoo** [comment]
Please assign this issue to me.

**Comment by KieranBond** [comment]
Hi @aseemsahoo - Any updates on this one?

**Comment by aseemsahoo** [comment]
Hi @KieranBond , I haven't started work on this issue yet, since I was busy with university commitments for the last 2 weeks. Since I'm free now, I'll be starting work on this issue today.
I'll give a PR in few days.
