### ISSUE TITLE
[FEATURE] Display the current playback context (Playlist, Album, Artist)

### ISSUE THREAD

**Issue by GabrielCoteM** [KieranBond/MiniSpotify#27]
* **Is your feature request related to a problem? Please describe.**

It's not related to a problem right now, but it's related to a feature I would like to request in the future, which would be to add an "Add To Playlist" button.

---

* **Describe the solution you'd like**

Show the current playback context of the currently playing track under the artist name. It could be an album, a playlist or an artist's page. Here's a mockup of the idea.

![mockup](https://user-images.githubusercontent.com/5678332/70398707-214ea580-19ec-11ea-8527-42d70a1a116e.png)

The Playback object obtained from GetPlayback() contains a Context object, which contains the Spotify URI that points to the current playlist, album or artist, as well as a string to identify the type of context. It should be possible to extract the ID from the URI, and use the type and the ID to get the right context's name.

**Comment by KieranBond** [comment]
I feel like this would leave a cluttered UI.

Whilst the later feature you would like sounds great and is something I also want, I'm not quite sure the need for this in relation?

Perhaps if we made the whole UI a bit larger this would fit better?

**Comment by GabrielCoteM** [comment]
> I feel like this would leave a cluttered UI.
> 
> Whilst the later feature you would like sounds great and is something I also want, I'm not quite sure the need for this in relation?
> 
> Perhaps if we made the whole UI a bit larger this would fit better?

Good point. I'll be making the feature request for the other feature soon then. Thanks!

**Comment by KieranBond** [comment]
> Good point. I'll be making the feature request for the other feature soon then. Thanks!

Feel free to try this anyways in a branch, and post a screenshot - I'd just make the whole Window bigger first.

I'll re-open until then.

**Comment by GabrielCoteM** [comment]
> > Good point. I'll be making the feature request for the other feature soon then. Thanks!
> 
> Feel free to try this anyways in a branch, and post a screenshot - I'd just make the whole Window bigger first.
> 
> I'll re-open until then.

Sure thing, then!
