### ISSUE TITLE
Error Relaying

### ISSUE THREAD

**Issue by KieranBond** [KieranBond/MiniSpotify#6]
Currently, we don't do anything with errors other than crash.. We should make sure there's some feedback from them, and that if we're going to crash we do it properly.

**Comment by Gusted** [comment]
I fixed 1 of those errors in #16 I don't have currently seen any other issue's

**Comment by Gusted** [comment]
I added more commits in #16 and So far i know with spamming buttons etc and make it hard I don't get anymore exit errors

**Comment by KieranBond** [comment]
So, @Gusted managed to handle some errors being thrown when the program was running - Whilst we don't handle crashing gracefully still, we've at least fixed some bugs when it comes to errors and hopefully won't crash from them. #16

**Comment by KieranBond** [comment]
@aseemsahoo's PR #38 has somewhat moved this ticket along also, and given us something to use if we want to revisit this topic. Closing for now and marking as done.
